apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: istio-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.10.10.50-10.10.10.60
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: istio-adv
  namespace: metallb-system
spec:
  ipAddressPools:
    - istio-pool

