apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortio-a
  labels:
    app: fortio-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortio-a
  template:
    metadata:
      labels:
        app: fortio-a
    spec:
      containers:
      - name: fortio
        image: fortio/fortio
        args: ["server"]
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelectorTerms:
             matchExpressions:
              - key: app
                operator: In
                values:
                - frontend
            topologyKey: "kubernetes.io/hostname"

