apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: frotend-cb
  namespace: test
spec:
  host: frontend.test.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
    outlierDetection:
      consecutiveErrors: 1
      interval: 1s
      baseEjectionTime: 30s
      maxEjectionPercent: 100

