apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: fortio-a-cb
  namespace: test
spec:
  host: fortio-a.default.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
    outlierDetection:
      consecutiveErrors: 1
      interval: 1s
      baseEjectionTime: 30s
      maxEjectionPercent: 100

